### PR TITLE
Remove (tacit) use of LoadWithPartialName with nunit.framework

### LINKED ISSUE #62: nunit.framework is loaded by partial name in nunit.core
This bug is similar to the one I fixed in NUnit 3, see there for further discussion: https://github.com/nunit/nunit-console/issues/367

In this case it's even simpler, since we have the actual assembly available to us and don't even need to load it at all. I'll submit a PR in a moment with a fix.

In NUnit 2, the problem is confined to activating ITestActions, as everything else is loaded correctly. This, however, is something we use a lot in our test suites.

(IMO Microsoft made a mistake by making it possible to load by partial name; it causes stuff to work...until it doesn't.)

### PR DESCRIPTION
**Pull request by cyanite**
Fix #62

### CODE REVIEW

**Comment by cyanite** [comment]
Alright, so this PR might have some problems. It did work locally. Anyway, I'll have a look at it tomorrow.

**Comment by cyanite** [comment]
Ok, so I found the bug, which isn't just in my code but in src/NUnitFramework/tests-net45/nunit.framework.tests.net45.csproj which forgets to define certain symbols (like NET_4_5) in release mode, leading to an empty assembly. So the tests are actually not run, but when I fix it, they pass.

I will probably still need to handle the case of a non-test assembly without throwing an exception. I'll update the PR with bug fixes. Just let me know if you want them separately instead.

**Comment by CharliePoole** [comment]
This looks good to me but I'd feel a bit better if there were a test that failed before your fix and passed afterwards. Any ideas of how to do that?

**Comment by cyanite** [comment]
All right, I updated the pull request with a test. It now has three changesets:

1. A test for running tests on assemblies with load policies. The test fails as per this changeset.
2. A fix for the issue. The test now succeeds.
3. The somewhat unrelated fix that defines some missing compile time constants to make sure tests are actually run.

**Pull request merged**
